#!/bin/sh

rootDir=`git rev-parse --show-toplevel`;

# if merging into master branch
if [ `git rev-parse --abbrev-ref HEAD` == "master" ]; then

    # file containing verion numbers
    fnVN=$rootDir/code/include/VersionNumber.h;

    # check if MAJOR flag is set
    if [ ${MAJOR+x} ]; then
        oldNum=`awk '/VERSION_NUMBER_MAJOR [0-9]+/ {print $3}' $fnVN`;
        newNum=$(($oldNum+1));
        sed -i "" -E "s/VERSION_NUMBER_MAJOR $oldNum/VERSION_NUMBER_MAJOR $newNum/g" $fnVN;
    else
        oldNum=`awk '/VERSION_NUMBER_MINOR [0-9]+/ {print $3}' $fnVN`;
        newNum=$(($oldNum+1));
        sed -i "" -E "s/VERSION_NUMBER_MINOR $oldNum/VERSION_NUMBER_MINOR $newNum/g" $fnVN;
    fi

    # reset build number
    oldNum=`awk '/BUILD_NUMBER [0-9]+/ {print $3}' $fnVN`;
    sed -i "" -E "s/BUILD_NUMBER $oldNum/BUILD_NUMBER 0/g" $fnVN;

    # ammend the commit with new version of VersionNumber.h
    git add $fnVN;
    git commit --amend -C HEAD --no-verify
fi
