#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.

filediff=`git diff`;

if [[ ! -z $filediff ]]; then
    echo "Je t'aime"
    
    rootDir=`git rev-parse --show-toplevel`;
    
    # If on develop branch
    if [ `git rev-parse --abbrev-ref HEAD` == "develop" ]; then
        # do development stuff
        git add $rootDir/code/include/VersionNumber.h;
        git commit --amend -C HEAD --no-verify
    
    elif [ `git rev-parse --abbrev-ref HEAD` == "master" ]; then
        # do master stuff
        echo "master branch";
        git add $rootDir/code/include/VersionNumber.h;
        git commit --amend -C HEAD --no-verify
    fi
fi
