#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.


if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# If you want to allow non-ASCII filenames set this variable to true.
allownonascii=$(git config --bool hooks.allownonascii)



# If there are whitespace errors, print the offending file names and fail.
#exec git diff-index --check --cached $against --


rootDir=`git rev-parse --show-toplevel`;

# check if elements are staged
git diff --cached --quiet --exit-code

# make sure there are staged elements
if [ $? -ne 0 ]; then       # something is staged   

    # If on develop branch
    if [ `git rev-parse --abbrev-ref HEAD` == "develop" ]; then
        # update build number
        oldNum=`awk '/BUILD_NUMBER [0-9]+/ {print $3}' $rootDir/code/include/VersionNumber.h`;
        newNum=$(($oldNum+1));
        sed -i "" -E "s/BUILD_NUMBER $oldNum/BUILD_NUMBER $newNum/g" $rootDir/code/include/VersionNumber.h;
    fi
fi
